import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/entities.dart';
import '../models/models.dart';
import 'irepositories.dart';

/// Bet repository implementation
class BetRepository implements IBetRepository {
  final SupabaseClient _supabase;

  BetRepository({required SupabaseClient supabase})
      : _supabase = supabase;

  @override
  Future<Bet> placeBet({
    required String userId,
    required String lotteryDrawId,
    required List<int> selectedNumbers,
    required double betAmount,
  }) async {
    // Validate selected numbers
    if (selectedNumbers.length != 6) {
      throw ArgumentError('Selected numbers must contain exactly 6 numbers');
    }

    // Calculate potential win (using default multiplier for now)
    final potentialWinAmount = betAmount * 1000000; // MATCH_6 multiplier

    final bet = Bet(
      id: '', // Will be generated by database
      userId: userId,
      lotteryDrawId: lotteryDrawId,
      selectedNumbers: selectedNumbers,
      betAmount: betAmount,
      status: BetStatus.pending,
      potentialWinAmount: potentialWinAmount,
      createdAt: DateTime.now(),
    );

    final model = BetModel.fromEntity(bet);

    final response = await _supabase
        .from('bets')
        .insert(model.toSupabase())
        .select()
        .single();

    // Update user's balance
    await _deductBalance(userId, betAmount);

    return BetModel.fromSupabase(response).toEntity();
  }

  @override
  Future<Bet?> getBetById(String betId) async {
    try {
      final response = await _supabase
          .from('bets')
          .select()
          .eq('id', betId)
          .maybeSingle();

      if (response == null) return null;

      final model = BetModel.fromSupabase(response);
      return model.toEntity();
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116') return null;
      rethrow;
    }
  }

  @override
  Future<List<Bet>> getUserBets({
    required String userId,
    BetStatus? status,
    int page = 1,
    int limit = 20,
  }) async {
    var query = _supabase
        .from('bets')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false)
        .range((page - 1) * limit, page * limit - 1);

    if (status != null) {
      query = query.eq('status', status.value);
    }

    final response = await query;
    return (response as List)
        .map((e) => BetModel.fromSupabase(e).toEntity())
        .toList();
  }

  @override
  Future<List<Bet>> getDrawBets(String drawId) async {
    final response = await _supabase
        .from('bets')
        .select()
        .eq('lottery_draw_id', drawId)
        .order('created_at', ascending: false);

    return (response as List)
        .map((e) => BetModel.fromSupabase(e).toEntity())
        .toList();
  }

  @override
  Future<List<Bet>> getUserPendingBets(String userId) async {
    return getUserBets(userId: userId, status: BetStatus.pending, limit: 100);
  }

  @override
  Future<List<Bet>> getUserWonBets(String userId) async {
    return getUserBets(userId: userId, status: BetStatus.won, limit: 100);
  }

  @override
  Future<List<Bet>> getUserLostBets(String userId) async {
    return getUserBets(userId: userId, status: BetStatus.lost, limit: 100);
  }

  @override
  Future<Bet> updateBetStatus(String betId, BetStatus status) async {
    final response = await _supabase
        .from('bets')
        .update({'status': status.value})
        .eq('id', betId)
        .select()
        .single();

    return BetModel.fromSupabase(response).toEntity();
  }

  @override
  Future<Bet> settleBet({
    required String betId,
    required BetStatus status,
    double? actualWinAmount,
    WinCriteria? winCriteria,
  }) async {
    final updateData = <String, dynamic>{
      'status': status.value,
      'settled_at': DateTime.now().toIso8601String(),
    };

    if (actualWinAmount != null) {
      updateData['actual_win_amount'] = actualWinAmount;
    }

    if (winCriteria != null) {
      updateData['win_criteria'] = winCriteria.value;
    }

    final response = await _supabase
        .from('bets')
        .update(updateData)
        .eq('id', betId)
        .select()
        .single();

    // If won, credit the user's balance
    if (status == BetStatus.won && actualWinAmount != null) {
      final bet = await getBetById(betId);
      if (bet != null) {
        await _creditBalance(bet.userId, actualWinAmount);
      }
    }

    return BetModel.fromSupabase(response).toEntity();
  }

  @override
  Future<int> getUserBetCountForDraw(String userId, String drawId) async {
    final response = await _supabase
        .from('bets')
        .select('id', count: CountOption.exact)
        .eq('user_id', userId)
        .eq('lottery_draw_id', drawId);

    return response.count ?? 0;
  }

  @override
  Future<double> calculatePotentialWin({
    required double betAmount,
    required WinCriteria criteria,
  }) async {
    // Get multiplier from game config
    final config = await _supabase
        .from('game_configs')
        .select('config_value')
        .eq('config_key', 'prize_multipliers')
        .single();

    final multipliers = config['config_value'] as Map<String, dynamic>;
    final multiplier = multipliers[criteria.value] as num? ?? 0;

    return betAmount * multiplier.toDouble();
  }

  /// Deduct amount from user's balance
  Future<void> _deductBalance(String userId, double amount) async {
    // Use RPC call for atomic balance update
    await _supabase.rpc(
      'update_balance',
      params: {
        'user_id': userId,
        'amount': -amount,
      },
    );
  }

  /// Credit amount to user's balance
  Future<void> _creditBalance(String userId, double amount) async {
    await _supabase.rpc(
      'update_balance',
      params: {
        'user_id': userId,
        'amount': amount,
      },
    );
  }
}
